# Generated by Django 5.0.6 on 2024-05-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rates_user_limit_company_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
