# Generated by Django 5.0.6 on 2024-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locaiton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
