# Generated by Django 5.0.6 on 2024-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
